### ISSUE TITLE
As an admin, I want to assign staff to roles so that they can access those resources

### ISSUE THREAD

**Issue by waiyan13** [techyangon/poly-api#4]
## Acceptance Criteria

Feature: Role assignment

    Scenario: the admin wants to assign user to role
        Given the user exists
        And the role exists
        And the role has assigned resources
        When the admin assigns the role to the user
        Then the user should be able to access those resources

## Tasks List

- [ ] Setup resources table
- [ ] Setup roles table
- [ ] Setup users table
